name: MScraper
on:
  schedule:
    - cron: '0 3 * * *' # Runs at 3 AM daily
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml
      - name: Run Scraper
        run: python m_scraper.py
      - name: Commit and Push XML
        run: |
          git config --global user.name 'MBot'
          git config --global user.email 'bot@machitech.com'
          git add linkedin-jobs.xml
          git commit -m "Auto-update job feed"
          git push
